-- Run in Supabase SQL editor if payout_config is missing.
create table if not exists payout_config (
  key text primary key,
  value integer not null default 0,
  updated_at timestamp not null default now()
);

-- coin_transactions is used for Financials -> View Transactions.
-- Only create it if your database does not already have it.
create table if not exists coin_transactions (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  discord_id text not null,
  amount integer not null,
  type text not null,
  description text not null,
  related_user_id text,
  created_at timestamp not null default now()
);

create index if not exists coin_transactions_user_created_idx
  on coin_transactions (discord_id, created_at desc);
